.\"-
.\" Copyright (c) 2021 Christos Margiolis <christos@FreeBSD.org>
.\"
.\" Permission is hereby granted, free of charge, to any person obtaining a copy
.\" of this software and associated documentation files (the "Software"), to deal
.\" in the Software without restriction, including without limitation the rights
.\" to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
.\" copies of the Software, and to permit persons to whom the Software is
.\" furnished to do so, subject to the following conditions:
.\"
.\" The above copyright notice and this permission notice shall be included in
.\" all copies or substantial portions of the Software.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
.\" IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
.\" FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
.\" AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
.\" LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
.\" OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
.\" THE SOFTWARE.
.\"

.Dd June 30, 2021
.Dt mixer 3
.Os
.Sh NAME
.Nm mixer
.Nd an OSS mixer library
.Sh LIBRARY
Mixer library (libmixer, -lmixer)
.Sh SYNOPSIS
.In mixer.h
.Ft struct mixer *
.Fn mixer_open "const char *path"
.Ft int
.Fn mixer_close "struct mixer *m"
.Ft struct mix_dev *
.Fn mixer_getdev "struct mixer *m" "int devno"
.Ft struct mix_dev *
.Fn mixer_getdevbyname "struct mixer *m" "name"
.Ft int
.Fn mixer_setvol "struct mixer *m" "float lvol" "float rvol"
.Ft int
.Fn mixer_setpan "struct mixer *m" "float pan"
.Ft int
.Fn mixer_setmute "struct mixer *m" "int opt"
.Ft int
.Fn mixer_modrecsrc "struct mixer *m" "int opt"
.Ft int
.Fn mixer_getdunit "void"
.Ft int
.Fn mixer_setdunit "struct mixer *m" "int unit"
.Ft int
.Fn mixer_getnmixers "void"
.Sh DESCRIPTION
.\" TODO
.Sh SEE ALSO
.Xr sound 4
.Sh AUTHORS
.An Christos Margiolis Aq Mt christos@margiolis.net
